### ISSUE TITLE
How does SHINE_color deal with transparent pixels in PNG images?

### ISSUE THREAD

**Issue by RenzoLanfranco** [RodDalBen/SHINE_color#11]
Hi. Excellent toolbox! How does SHINE_color deal with transparent pixels in PNG files, which typically have an alpha channel? I'm asking because I couldn't find any information about it in the Github and papers that describe how the toolbox works. If the toolbox ignores them, it would be great to know. If it doesn't ignore them, it would be great to have the option to ignore them.

Best!

**Comment by RodDalBen** [comment]
Hi Renzo, glad to hear that SHINE_color is being useful in your work. This is a good question. Right now the toolbox will transform any transparent pixel into a colorful pixel. After considering several options, we decided not to develop this feature at this time. But we did add a note with two pieces of information. If users choose `png` as their image format, a note will inform the user about the toolbox behavior (replacing transparent pixels with colorful ones); it also suggest that users choose to manipulate fore and background separately and then remove the background in an image processing software like GIMP or Photoshop.
