### ISSUE TITLE
Error: Out of memory

### ISSUE THREAD

**Issue by neurochenhe** [RodDalBen/SHINE_color#14]
Hello dear developer, thank you for such a great toolkit. I have a query I would like to ask you to answer, I would like to normalize some videos (about 40 videos, each video is 5 seconds long, 30fps) with low-level visual features, I found that the toolkit can only operate on a single video, so I performed frame extraction on each video, and when I tried to process the extracted frames as images (8450 images for the test), I got the message that I don't have enough memory again. I would like to ask the developer if there is a proper operation to do if I want to achieve what I mentioned earlier, i.e. normalize more than one video. Thanks!

Below is the log message:

SHINE_color - Log created on 2023-11-01 21:15:28
 
Input     [1=images, 2=video]: 1
Type the image format  [e.g., jpg, png]: png

Please note that our toolbox does not support transparent backgrounds.
Transparent backgrounds will be converted during manipulations.
Please manipulate the fore and background separately, and then remove the background
in an image processing software (e.g., GIMP).

Select the colorspace to perform the manipulations    [1=HSV, 2=CIELab, 3=RGB, 4=Greyscale]: 3
Do you want diagnostic plots? (may take some time)    [1=yes, 2=no]: 2
SHINE_color options    [1=default, 2=custom]: 1
 
Number of images: 8450
 
Option:   specMatch & histMatch with 1 iteration(s)
Option:   whole image
Error: Out of memory.

**Comment by RodDalBen** [comment]
Hi @neurochenhe, we have encountered the "out of memory" issues before when dealing with videos. Most of the times we solved the problems by getting more memory and/or reducing the size of the videos. If you can't reduce the size of the videos, you will need more memory--there is no way around it. If you can reduce the videos, then you could start with resolution (Full HD -> HD and so on) and downsampling. I hope this helps!

**Comment by neurochenhe** [comment]
Thanks for the heads up, I will follow the tips you gave to try and improve.
