### ISSUE TITLE
'Statement of need' section required

### ISSUE THREAD

**Issue by da5nsy** [RodDalBen/SHINE_color#2]
As per [here](https://joss.readthedocs.io/en/latest/review_criteria.html#a-statement-of-need) and noted by @whedon [here](https://github.com/openjournals/joss-reviews/issues/3449#issuecomment-873371380).

~~At minimum, I think you could probably rename the summary section to 'Statement of need'.~~ I've just seen that [here](https://joss.readthedocs.io/en/latest/review_checklist.html#documentation) that both summary and statement of need sections are required.

**Comment by RodDalBen** [comment]
Right! I added a brief summary and renamed the former "summary" to Statement of need. Thank you!
