### ISSUE TITLE
Tutorial tweak

### ISSUE THREAD

**Issue by da5nsy** [RodDalBen/SHINE_color#4]
(as part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/3449))

In [the tutorial](https://github.com/RodDalBen/SHINE_color#tutorial), I think that either point 3 should direct the user to navigate to SHINE_color\toolbox, or there should be an additional point instructing the user to add the folder and subfolders to the path.

**Comment by RodDalBen** [comment]
Done. I added a step and included instructions to go to the subfolder "SHINE_color/toolbox".
